export const AppConstants = {
  appName: 'GATO',
  tagline: 'Small Can Grow',
  taglineKirundi: 'Gito Can Cane',
  defaultCurrency: 'BIF',
  supportedCurrencies: ['BIF', 'USD', 'EUR', 'RWF', 'KES', 'TZS', 'UGX', 'XOF', 'ZMW'],
  supportedLanguages: ['en', 'fr', 'rn', 'sw', 'rw'],
  supportedLanguageNames: {
    'en': 'English',
    'fr': 'Français',
    'rn': 'Kirundi',
    'sw': 'Kiswahili',
    'rw': 'Kinyarwanda',
  },
  defaultLanguage: 'rn',
  dataSyncMaxRetries: 3,
  dataSyncBatchSize: 50,
  offlineModeEnabled: true,
  smsEnabled: true,
  ussdEnabled: true,
  whatsappEnabled: true,
  voiceEnabled: true,
  trustScoreBaseMax: 100,
  trustScoreEmergencyMin: 41,
  trustScoreWorkingCapitalMin: 61,
  trustScoreInventoryMin: 76,
  pages: {
    onboarding: '/onboarding',
    dashboard: '/',
    sales: '/sales',
    expenses: '/expenses',
    inventory: '/inventory',
    reports: '/reports',
    savings: '/savings',
    profile: '/profile',
    community: '/community',
    coach: '/coach',
    credit: '/credit',
    loans: '/loans',
    voice: '/voice',
  },
  smsShortcode: 'GATO',
  ussdCode: '*123#',
  whatsAppBusinessNumber: '+25700000000',
  maxLoanAmountWorkingCapital: 300,
  maxLoanAmountInventory: 1000,
  maxLoanAmountEmergency: 50,
};
